PARA = {
 2:  [("Peter Ferenc", True)],
 3:  [("Rammelkam 2, 84036 Kumhausen, Germania", True)],
 6:  [("Tribunale dell'Unione europea", True)],
 7:  [("Cancelleria del Tribunale", False)],
 8:  [("Rue du Fort Niedergrünewald L-2925 Lussemburgo", False)],
 11: [("24.12.2025", True)],
 13: [("Oggetto:", True), (" Risposta alla comunicazione relativa all'impossibilità di accogliere la domanda di apertura di un account di accesso all'applicazione e-Curia", False)],
 14: [("Numero di riferimento:", True), (" DEM10029674", False)],
 16: [("RISPOSTA ALLA COMUNICAZIONE DI RIGETTO DELLA DOMANDA DI ACCESSO A e-CURIA", True)],
 19: [("Signor Cancelliere,", False)],
 21: [("Accuso ricevuta della Vostra comunicazione del 22 dicembre 2025, con la quale mi è stato comunicato che la mia domanda di apertura di un account di accesso all'applicazione e-Curia non poteva essere accolta per il mancato rispetto di determinate condizioni formali.", False)],
 22: [("Mi permetto di esporre i seguenti elementi, al solo fine di chiarimento procedurale della situazione:", False)],
 23: [("La mia domanda di accesso all'applicazione e-Curia non è stata presentata al fine di agire in qualità di rappresentante di altre persone, di uno Stato membro o di un'istituzione dell'Unione europea", True), (", bensì", False)],
 24: [("esclusivamente in qualità di persona fisica – potenziale ricorrente.", False)],
 25: [("Prendo atto che ", False), ("l'apertura di un account di accesso e-Curia è subordinata alla qualità di avvocato o di rappresentante abilitato", True), (" e che, in quanto persona fisica priva di tale abilitazione, non soddisfo le condizioni per la sua apertura.", False)],
 26: [("Confermo altresì espressamente di essere consapevole che ", False), ("la proposizione di un ricorso di competenza del Tribunale dell'Unione europea richiede obbligatoriamente la rappresentanza da parte di un avvocato", True), (" abilitato a esercitare dinanzi a un organo giurisdizionale di uno Stato membro o di uno Stato parte dell'accordo SEE.", False)],
 28: [("In relazione a quanto precede, mi permetto di indicare che ", False), ("sto attualmente preparando il deposito di una domanda di gratuito patrocinio ai sensi degli articoli da 146 a 150 del regolamento di procedura del Tribunale", True), (", destinata a costituire il presupposto processuale per la designazione di un rappresentante legale; con la presente Ve ne informo. La domanda è depositata parallelamente anche in forma cartacea, conformemente al regolamento di procedura.", False)],
 29: [("La presente risposta ha carattere esclusivamente ", False), ("informativo e di chiarimento procedurale ", True), ("e non mira al riesame della decisione di non concedere l'accesso all'applicazione e-Curia.", False)],
 30: [("In relazione all'elenco delle condizioni non soddisfatte che mi è stato comunicato, mi permetto di precisare quanto segue:", False)],
 31: [("Il modulo di domanda l'ho ", False), ("stampato, firmato di mio pugno e inviato per posta raccomandata con consegna a mani proprie ", True), ("all'indirizzo del Tribunale dell'Unione europea, conformemente all'articolo 147, paragrafo 6, del regolamento di procedura.", False)],
 32: [("Rilevo inoltre che, nella comunicazione ricevuta, ", False), ("non sono contrassegnati né il punto 1 né il punto 2", True), (", ", False), ("né il punto 4,", True)],
 33: [("ossia né la firma del modulo né la copia del documento d'identità, quali condizioni non soddisfatte. È contrassegnato esclusivamente il punto 3, relativo all'abilitazione a rappresentare in un procedimento dinanzi a un organo giurisdizionale.", False)],
 34: [("Mi permetto di sottolineare che ", False), ("non ho chiesto l'accesso all'applicazione e-Curia in qualità di avvocato né di rappresentante di terzi", True), (", bensì come persona fisica – potenziale ricorrente. In tale contesto, l'abilitazione di cui al punto 3 non può costituire una condizione pertinente", False)],
 35: [("di rigetto della mia domanda di apertura di un account di accesso all'applicazione e-Curia del 19/12/2025, registrata come ", False), ("DEM10029674.", True)],
 36: [("Pertanto mi permetto di chiedere una precisazione nel merito,", True)],
 37: [("se il mio invio cartaceo, firmato di mio pugno, sia stato ricevuto e registrato,", False)],
 38: [("e per quale motivo la comunicazione faccia riferimento al mancato rispetto della condizione di cui al punto 3, che non si applica alla mia qualità di persona fisica – potenziale ricorrente, indicando il fondamento giuridico.", False)],
 39: [("Mi permetto altresì di informarVi che, a causa della mia insolvenza, deposito parallelamente alla presente risposta una domanda di gratuito patrocinio e di designazione di un rappresentante legale, conformemente agli articoli da 146 a 150 del regolamento di procedura del Tribunale.", False)],
 40: [("Entrambi i documenti sono trasmessi via posta elettronica con firma elettronica qualificata (QES), nel prosieguo della corrispondenza elettronica in corso con la Cancelleria del Tribunale.", False)],
 41: [("L'invio ha carattere documentale e informativo. Il deposito regolare sarà effettuato conformemente al regolamento di procedura.", False)],
}
LABELS = {4: [("E-Mail:", "E-mail:"), ("Telefon:", "Telefono:")], 9: [("E-Mail:", "E-mail:")]}
BOXES = {"S úctou": "Con osservanza,", "V Kumhausene 24.12.2025": "Kumhausen, 24.12.2025"}
