PARA = {
 2:  [("Peter Ferenc", True)],
 3:  [("Rammelkam 2, 84036 Kumhausen, Njemačka", True)],
 6:  [("Opći sud Europske unije", True)],
 7:  [("Tajništvo Suda", False)],
 8:  [("Rue du Fort Niedergrünewald L-2925 Luxembourg", False)],
 11: [("24.12.2025.", True)],
 13: [("Predmet:", True), (" Odgovor na obavijest o nemogućnosti udovoljavanja zahtjevu za otvaranje pristupnog računa za aplikaciju e-Curia", False)],
 14: [("Referentni broj:", True), (" DEM10029674", False)],
 16: [("ODGOVOR NA OBAVIJEST O ODBIJANJU ZAHTJEVA ZA PRISTUP APLIKACIJI e-CURIA", True)],
 19: [("Poštovani gospodine tajniče,", False)],
 21: [("Potvrđujem primitak Vaše obavijesti od 22. prosinca 2025., kojom sam obaviješten da se mojem zahtjevu za otvaranje pristupnog računa za aplikaciju e-Curia ne može udovoljiti zbog neispunjavanja određenih formalnih uvjeta.", False)],
 22: [("Dopuštam si iznijeti sljedeće činjenice, isključivo radi postupovnog razjašnjenja situacije:", False)],
 23: [("Moj zahtjev za pristup aplikaciji e-Curia nije podnesen s ciljem zastupanja drugih osoba, države članice niti institucije Europske unije", True), (", nego", False)],
 24: [("isključivo u svojstvu fizičke osobe – potencijalnog tužitelja.", False)],
 25: [("Primam na znanje da je ", False), ("otvaranje pristupnog računa e-Curia vezano uz svojstvo odvjetnika ili ovlaštenog zastupnika", True), (", te da kao fizička osoba bez takvog ovlaštenja ne ispunjavam uvjete za njegovo otvaranje.", False)],
 26: [("Ujedno izričito potvrđujem da sam svjestan činjenice da je ", False), ("za podnošenje tužbe o kojoj je nadležan odlučivati Opći sud Europske unije obvezno zastupanje po odvjetniku", True), (" ovlaštenom za postupanje pred sudom države članice ili države stranke Sporazuma o EGP-u.", False)],
 28: [("U vezi s navedenim dopuštam si istaknuti da ", False), ("trenutačno pripremam podnošenje zahtjeva za dodjelu besplatne pravne pomoći na temelju članaka 146. do 150. Poslovnika Općeg suda", True), (", koji treba poslužiti kao postupovna pretpostavka za imenovanje pravnog zastupnika te Vas o toj činjenici ovime obavješćujem; zahtjev je usporedno podnesen i u pisanom obliku u skladu s Poslovnikom.", False)],
 29: [("Ovaj odgovor ima isključivo ", False), ("informativni i postupovno razjašnjavajući karakter ", True), ("i nije usmjeren na ponovno preispitivanje odluke o neodobravanju pristupa aplikaciji e-Curia.", False)],
 30: [("Slijedom navedenog popisa neispunjenih uvjeta dopuštam si iznijeti sljedeće pojašnjenje:", False)],
 31: [("Obrazac zahtjeva sam ", False), ("ispisao, vlastoručno potpisao i poslao poštom preporučeno s povratnicom ", True), ("na adresu Općeg suda Europske unije, u skladu s člankom 147. stavkom 6. Poslovnika.", False)],
 32: [("Ujedno ukazujem na to da u zaprimljenoj obavijesti ", False), ("nisu označene točke 1. ni 2.", True), (", ", False), ("ni 4.,", True)],
 33: [("tj. potpis obrasca ni preslika osobne isprave, kao neispunjeni uvjeti. Označena je isključivo točka 3., koja se odnosi na ovlaštenje za zastupanje u postupku pred sudskim tijelom.", False)],
 34: [("Dopuštam si naglasiti da ", False), ("nisam tražio pristup aplikaciji e-Curia u svojstvu odvjetnika niti zastupnika trećih osoba", True), (", nego kao fizička osoba – potencijalni tužitelj. U tom kontekstu ovlaštenje iz točke 3. ne može biti mjerodavan uvjet", False)],
 35: [("odbijanja mojeg zahtjeva za otvaranje pristupnog računa za aplikaciju e-Curia od 19.12.2025., označenog kao ", False), ("DEM10029674.", True)],
 36: [("Stoga si dopuštam zatražiti sadržajno pojašnjenje,", True)],
 37: [("je li moj papirnati, vlastoručno potpisani podnesak zaprimljen i evidentiran,", False)],
 38: [("i iz kojeg razloga se u obavijesti ukazuje na neispunjenje uvjeta iz točke 3., koji se ne odnosi na moje svojstvo fizičke osobe – potencijalnog tužitelja, uz navođenje pravne osnove.", False)],
 39: [("Ujedno si dopuštam obavijestiti Vas da zbog svoje insolventnosti usporedno s ovim odgovorom podnosim zahtjev za dodjelu besplatne pravne pomoći i imenovanje pravnog zastupnika, u skladu s člancima 146. do 150. Poslovnika Općeg suda.", False)],
 40: [("Oba dokumenta poslana su e-poštom kao elektronički potpisana (QES), u nastavku tekuće komunikacije e-poštom s Tajništvom Suda.", False)],
 41: [("Slanje ima dokumentacijski i informativni karakter. Uredno podnošenje bit će izvršeno u skladu s Poslovnikom.", False)],
}
LABELS = {4: [("E-Mail:", "E-pošta:"), ("Telefon:", "Telefon:")], 9: [("E-Mail:", "E-pošta:")]}
BOXES = {"S úctou": "S poštovanjem,", "V Kumhausene 24.12.2025": "U Kumhausenu, 24.12.2025."}
