PARA = {
 2:  [("Peter Ferenc", True)],
 3:  [("Rammelkam 2, 84036 Kumhausen, Tyskland", True)],
 6:  [("Europeiska unionens tribunal", True)],
 7:  [("Tribunalens kansli", False)],
 8:  [("Rue du Fort Niedergrünewald L-2925 Luxemburg", False)],
 11: [("24.12.2025", True)],
 13: [("Ärende:", True), (" Svar på meddelandet om att ansökan om öppnande av ett åtkomstkonto till applikationen e-Curia inte kan bifallas", False)],
 14: [("Referensnummer:", True), (" DEM10029674", False)],
 16: [("SVAR PÅ MEDDELANDET OM AVSLAG PÅ ANSÖKAN OM ÅTKOMST TILL e-CURIA", True)],
 19: [("Herr justitiesekreterare,", False)],
 21: [("Jag bekräftar mottagandet av Ert meddelande av den 22 december 2025, genom vilket jag underrättades om att min ansökan om öppnande av ett åtkomstkonto till applikationen e-Curia inte kunde bifallas på grund av att vissa formella villkor inte var uppfyllda.", False)],
 22: [("Jag tillåter mig att anföra följande omständigheter, uteslutande i syfte att processuellt klargöra situationen:", False)],
 23: [("Min ansökan om åtkomst till applikationen e-Curia lämnades inte in i syfte att uppträda som ombud för andra personer, för en medlemsstat eller för en av Europeiska unionens institutioner", True), (", utan", False)],
 24: [("uteslutande i egenskap av fysisk person – potentiell sökande.", False)],
 25: [("Jag noterar att ", False), ("öppnandet av ett åtkomstkonto till e-Curia är knutet till ställningen som advokat eller behörigt ombud", True), (" och att jag som fysisk person utan sådan behörighet inte uppfyller villkoren för att öppna ett sådant konto.", False)],
 26: [("Jag bekräftar samtidigt uttryckligen att jag är medveten om att ", False), ("det för väckande av talan som Europeiska unionens tribunal är behörig att pröva krävs obligatoriskt ombud genom advokat", True), (" som är behörig att uppträda inför domstol i en medlemsstat eller i en stat som är part i EES-avtalet.", False)],
 28: [("Med anledning av det ovan anförda tillåter jag mig att uppge att ", False), ("jag för närvarande förbereder en ansökan om rättshjälp enligt artiklarna 146–150 i tribunalens rättegångsregler", True), (", vilken ska utgöra den processuella förutsättningen för förordnande av ett rättsligt ombud; härmed informerar jag Er om detta. Ansökan ges parallellt in även i pappersform i enlighet med rättegångsreglerna.", False)],
 29: [("Detta svar har uteslutande ", False), ("informativ och processuellt klargörande karaktär ", True), ("och syftar inte till en omprövning av beslutet att inte bevilja åtkomst till applikationen e-Curia.", False)],
 30: [("Med anledning av den översända förteckningen över ej uppfyllda villkor tillåter jag mig att lämna följande precisering:", False)],
 31: [("Ansökningsformuläret har jag ", False), ("skrivit ut, undertecknat egenhändigt och sänt per rekommenderat brev med mottagningsbevis ", True), ("till Europeiska unionens tribunal, i enlighet med artikel 147.6 i rättegångsreglerna.", False)],
 32: [("Jag påpekar vidare att det i det mottagna meddelandet ", False), ("varken är markerat punkt 1 eller punkt 2", True), (", ", False), ("eller punkt 4,", True)],
 33: [("det vill säga varken undertecknandet av formuläret eller kopian av identitetshandlingen, som ej uppfyllda villkor. Endast punkt 3 är markerad, vilken avser behörigheten att företräda i ett förfarande inför ett rättskipande organ.", False)],
 34: [("Jag tillåter mig att understryka att ", False), ("jag inte ansökte om åtkomst till applikationen e-Curia i egenskap av advokat eller ombud för tredje man", True), (", utan som fysisk person – potentiell sökande. I detta sammanhang kan behörigheten enligt punkt 3 inte utgöra ett relevant villkor", False)],
 35: [("för avslag på min ansökan om öppnande av ett åtkomstkonto till applikationen e-Curia av den 19/12/2025, registrerad som ", False), ("DEM10029674.", True)],
 36: [("Därför tillåter jag mig att begära ett sakligt klargörande,", True)],
 37: [("huruvida min pappersinlaga, egenhändigt undertecknad, har mottagits och registrerats,", False)],
 38: [("och av vilket skäl meddelandet hänvisar till att villkoret i punkt 3 inte är uppfyllt, vilket inte är tillämpligt på min ställning som fysisk person – potentiell sökande, med angivande av den rättsliga grunden.", False)],
 39: [("Jag tillåter mig även att informera om att jag på grund av min insolvens parallellt med detta svar ger in en ansökan om rättshjälp och om förordnande av ett rättsligt ombud, i enlighet med artiklarna 146–150 i tribunalens rättegångsregler.", False)],
 40: [("Båda handlingarna översänds per e-post med kvalificerad elektronisk underskrift (QES), i anslutning till den pågående e-postkorrespondensen med tribunalens kansli.", False)],
 41: [("Översändandet har dokumenterande och informativ karaktär. Regelrätt ingivande kommer att ske i enlighet med rättegångsreglerna.", False)],
}
LABELS = {4: [("E-Mail:", "E-post:"), ("Telefon:", "Telefon:")], 9: [("E-Mail:", "E-post:")]}
BOXES = {"S úctou": "Högaktningsfullt,", "V Kumhausene 24.12.2025": "Kumhausen, 24.12.2025"}
