PARA = {
 2:  [("Peter Ferenc", True)],
 3:  [("Rammelkam 2, 84036 Kumhausen, Niemcy", True)],
 6:  [("Sąd Unii Europejskiej", True)],
 7:  [("Sekretariat Sądu", False)],
 8:  [("Rue du Fort Niedergrünewald L-2925 Luxembourg", False)],
 11: [("24.12.2025 r.", True)],
 13: [("Dotyczy:", True), (" Odpowiedź na zawiadomienie o niemożności uwzględnienia wniosku o otwarcie konta dostępu do aplikacji e-Curia", False)],
 14: [("Numer referencyjny:", True), (" DEM10029674", False)],
 16: [("ODPOWIEDŹ NA ZAWIADOMIENIE O ODMOWIE UWZGLĘDNIENIA WNIOSKU O DOSTĘP DO e-CURIA", True)],
 19: [("Szanowny Panie Sekretarzu,", False)],
 21: [("Potwierdzam otrzymanie Państwa zawiadomienia z dnia 22 grudnia 2025 r., w którym poinformowano mnie, że mój wniosek o otwarcie konta dostępu do aplikacji e-Curia nie może zostać uwzględniony z powodu niespełnienia określonych warunków formalnych.", False)],
 22: [("Pozwalam sobie przedstawić następujące okoliczności, wyłącznie w celu proceduralnego wyjaśnienia sytuacji:", False)],
 23: [("Mój wniosek o dostęp do aplikacji e-Curia nie został złożony w celu działania jako przedstawiciel innych osób, państwa członkowskiego ani instytucji Unii Europejskiej", True), (", lecz", False)],
 24: [("wyłącznie w charakterze osoby fizycznej – potencjalnego skarżącego.", False)],
 25: [("Przyjmuję do wiadomości, że ", False), ("otwarcie konta dostępu e-Curia jest uzależnione od statusu adwokata lub uprawnionego przedstawiciela", True), (" oraz że jako osoba fizyczna nieposiadająca takiego uprawnienia nie spełniam warunków jego otwarcia.", False)],
 26: [("Jednocześnie wyraźnie potwierdzam, że mam świadomość, iż ", False), ("wniesienie skargi, do której rozpoznania właściwy jest Sąd Unii Europejskiej, wymaga obowiązkowego zastępstwa przez adwokata", True), (" uprawnionego do występowania przed sądem państwa członkowskiego lub państwa będącego stroną Porozumienia EOG.", False)],
 28: [("W nawiązaniu do powyższego pozwalam sobie wskazać, że ", False), ("obecnie przygotowuję złożenie wniosku o przyznanie pomocy prawnej na podstawie artykułów 146–150 regulaminu postępowania przed Sądem", True), (", który ma stanowić proceduralną przesłankę wyznaczenia pełnomocnika, o czym niniejszym informuję; wniosek został równolegle złożony również w formie papierowej zgodnie z regulaminem postępowania.", False)],
 29: [("Niniejsza odpowiedź ma wyłącznie ", False), ("informacyjny i proceduralnie wyjaśniający charakter ", True), ("i nie zmierza do ponownego rozpatrzenia decyzji o nieotwarciu dostępu do aplikacji e-Curia.", False)],
 30: [("W nawiązaniu do przekazanego wykazu niespełnionych warunków pozwalam sobie przedstawić następujące uściślenie:", False)],
 31: [("Formularz wniosku ", False), ("wydrukowałem, własnoręcznie podpisałem i wysłałem pocztą listem poleconym za potwierdzeniem odbioru ", True), ("na adres Sądu Unii Europejskiej, zgodnie z artykułem 147 ustęp 6 regulaminu postępowania.", False)],
 32: [("Jednocześnie zwracam uwagę, że w doręczonym zawiadomieniu ", False), ("nie zostały zaznaczone punkty 1 ani 2", True), (", ", False), ("ani 4,", True)],
 33: [("tj. podpis formularza ani kopia dokumentu tożsamości, jako warunki niespełnione. Zaznaczony jest wyłącznie punkt 3, dotyczący uprawnienia do reprezentowania w postępowaniu przed organem sądowym.", False)],
 34: [("Pozwalam sobie podkreślić, że ", False), ("nie wnioskowałem o dostęp do aplikacji e-Curia w charakterze adwokata ani przedstawiciela osób trzecich", True), (", lecz jako osoba fizyczna – potencjalny skarżący. W tym kontekście uprawnienie z punktu 3 nie może stanowić właściwego warunku", False)],
 35: [("odmowy uwzględnienia mojego wniosku o otwarcie konta dostępu do aplikacji e-Curia z dnia 19.12.2025, oznaczonego jako ", False), ("DEM10029674.", True)],
 36: [("W związku z tym pozwalam sobie zwrócić się o merytoryczne uściślenie,", True)],
 37: [("czy moje papierowe, własnoręcznie podpisane pismo zostało doręczone i zarejestrowane,", False)],
 38: [("oraz z jakiego powodu w zawiadomieniu wskazuje się na niespełnienie warunku z punktu 3, który nie odnosi się do mojego statusu osoby fizycznej – potencjalnego skarżącego, wraz ze wskazaniem podstawy prawnej.", False)],
 39: [("Jednocześnie pozwalam sobie poinformować, że z powodu mojej niewypłacalności równolegle z niniejszą odpowiedzią składam wniosek o przyznanie pomocy prawnej i wyznaczenie pełnomocnika, zgodnie z artykułami 146–150 regulaminu postępowania przed Sądem.", False)],
 40: [("Oba dokumenty zostały przesłane pocztą elektroniczną jako podpisane elektronicznie (QES), w nawiązaniu do trwającej korespondencji elektronicznej z Sekretariatem Sądu.", False)],
 41: [("Przesłanie ma charakter dokumentacyjny i informacyjny. Prawidłowe złożenie nastąpi zgodnie z regulaminem postępowania.", False)],
}
LABELS = {4: [("E-Mail:", "E-mail:"), ("Telefon:", "Telefon:")], 9: [("E-Mail:", "E-mail:")]}
BOXES = {"S úctou": "Z poważaniem,", "V Kumhausene 24.12.2025": "Kumhausen, 24.12.2025 r."}
