PARA = {
 2:  [("Peter Ferenc", True)],
 3:  [("Rammelkam 2, 84036 Kumhausen, Alemania", True)],
 6:  [("Tribunal General de la Unión Europea", True)],
 7:  [("Secretaría del Tribunal", False)],
 8:  [("Rue du Fort Niedergrünewald L-2925 Luxemburgo", False)],
 11: [("24.12.2025", True)],
 13: [("Asunto:", True), (" Respuesta a la comunicación relativa a la imposibilidad de atender la solicitud de apertura de una cuenta de acceso a la aplicación e-Curia", False)],
 14: [("Número de referencia:", True), (" DEM10029674", False)],
 16: [("RESPUESTA A LA COMUNICACIÓN DE DENEGACIÓN DE LA SOLICITUD DE ACCESO A e-CURIA", True)],
 19: [("Señor Secretario,", False)],
 21: [("Acuso recibo de su comunicación de 22 de diciembre de 2025, mediante la cual se me informó de que no podía atenderse mi solicitud de apertura de una cuenta de acceso a la aplicación e-Curia por no cumplirse determinados requisitos formales.", False)],
 22: [("Me permito exponer los siguientes hechos, con la única finalidad de aclarar procesalmente la situación:", False)],
 23: [("Mi solicitud de acceso a la aplicación e-Curia no se presentó con el fin de actuar como representante de otras personas, de un Estado miembro ni de una institución de la Unión Europea", True), (", sino", False)],
 24: [("exclusivamente en calidad de persona física – demandante potencial.", False)],
 25: [("Tomo nota de que ", False), ("la apertura de una cuenta de acceso e-Curia está vinculada a la condición de abogado o de representante habilitado", True), (" y de que, como persona física sin tal habilitación, no cumplo los requisitos para su apertura.", False)],
 26: [("Asimismo confirmo expresamente ser consciente de que ", False), ("la interposición de un recurso cuya resolución es competencia del Tribunal General de la Unión Europea exige obligatoriamente la representación por un abogado", True), (" facultado para ejercer ante un órgano jurisdiccional de un Estado miembro o de un Estado parte del Acuerdo EEE.", False)],
 28: [("En relación con lo anterior, me permito indicar que ", False), ("actualmente estoy preparando la presentación de una solicitud de justicia gratuita conforme a los artículos 146 a 150 del Reglamento de Procedimiento del Tribunal General", True), (", que ha de servir como presupuesto procesal para la designación de representante legal, de lo cual les informo por la presente; la solicitud se presenta paralelamente también en formato papel conforme al Reglamento de Procedimiento.", False)],
 29: [("La presente respuesta tiene carácter exclusivamente ", False), ("informativo y de aclaración procesal ", True), ("y no pretende un nuevo examen de la decisión de no otorgar el acceso a la aplicación e-Curia.", False)],
 30: [("En relación con la lista de requisitos no cumplidos que me fue comunicada, me permito precisar lo siguiente:", False)],
 31: [("El formulario de solicitud lo ", False), ("imprimí, firmé de mi puño y letra y lo envié por correo certificado con acuse de recibo en mano propia ", True), ("a la dirección del Tribunal General de la Unión Europea, conforme al artículo 147, apartado 6, del Reglamento de Procedimiento.", False)],
 32: [("Asimismo señalo que, en la comunicación recibida, ", False), ("no están marcados los puntos 1 ni 2", True), (", ", False), ("ni el 4,", True)],
 33: [("es decir, ni la firma del formulario ni la copia del documento de identidad, como requisitos no cumplidos. Únicamente está marcado el punto 3, relativo a la habilitación para representar en un procedimiento ante un órgano jurisdiccional.", False)],
 34: [("Me permito subrayar que ", False), ("no solicité el acceso a la aplicación e-Curia en calidad de abogado ni de representante de terceros", True), (", sino como persona física – demandante potencial. En este contexto, la habilitación del punto 3 no puede constituir un requisito pertinente", False)],
 35: [("para denegar mi solicitud de apertura de una cuenta de acceso a la aplicación e-Curia de 19/12/2025, registrada como ", False), ("DEM10029674.", True)],
 36: [("Por ello me permito solicitar una precisión sobre el fondo,", True)],
 37: [("si mi escrito en papel, firmado de mi puño y letra, fue recibido y registrado,", False)],
 38: [("y por qué motivo la comunicación señala el incumplimiento del requisito del punto 3, que no se aplica a mi condición de persona física – demandante potencial, indicando el fundamento jurídico.", False)],
 39: [("Asimismo me permito informar de que, debido a mi insolvencia, presento paralelamente a esta respuesta una solicitud de justicia gratuita y de designación de representante legal, conforme a los artículos 146 a 150 del Reglamento de Procedimiento del Tribunal General.", False)],
 40: [("Ambos documentos se remiten por correo electrónico firmados electrónicamente (QES), en el marco de la correspondencia electrónica en curso con la Secretaría del Tribunal.", False)],
 41: [("El envío tiene carácter documental e informativo. La presentación regular se efectuará conforme al Reglamento de Procedimiento.", False)],
}
LABELS = {4: [("E-Mail:", "Correo electrónico:"), ("Telefon:", "Teléfono:")], 9: [("E-Mail:", "Correo electrónico:")]}
BOXES = {"S úctou": "Atentamente,", "V Kumhausene 24.12.2025": "Kumhausen, 24.12.2025"}
